-- Urban Furniture Accounting System
-- PostgreSQL database schema
-- Run this file on an empty Urban Furniture database.
-- Prices and amounts are stored as INTEGER paise. Example: 150000 = Rs. 1,500.00

CREATE TABLE accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE analytic_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    mobile VARCHAR(32),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(20),
    profile_image VARCHAR(512),
    is_archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    sales_price_cents INTEGER NOT NULL,
    cost_cents INTEGER NOT NULL,
    category VARCHAR(100),
    is_archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE budgets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    period VARCHAR(100) NOT NULL,
    responsible_person VARCHAR(255),
    planned_amount_cents INTEGER NOT NULL,
    analytic_account_id INTEGER NOT NULL REFERENCES analytic_accounts(id),
    start_date DATE,
    end_date DATE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE journals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    default_account_id INTEGER REFERENCES accounts(id),
    is_archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE purchase_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id INTEGER NOT NULL REFERENCES contacts(id),
    analytic_account_id INTEGER REFERENCES analytic_accounts(id),
    order_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
);

CREATE TABLE sales_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES contacts(id),
    analytic_account_id INTEGER REFERENCES analytic_accounts(id),
    order_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    login_id VARCHAR(32) UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    contact_id INTEGER REFERENCES contacts(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE journal_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id INTEGER NOT NULL REFERENCES journals(id),
    date DATE NOT NULL,
    reference VARCHAR(255)
);

CREATE TABLE purchase_order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id INTEGER NOT NULL REFERENCES purchase_orders(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price_cents INTEGER NOT NULL,
    tax_percent INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE sales_order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id INTEGER NOT NULL REFERENCES sales_orders(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price_cents INTEGER NOT NULL,
    tax_percent INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE customer_invoices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id INTEGER NOT NULL UNIQUE REFERENCES sales_orders(id),
    invoice_date DATE NOT NULL,
    due_date DATE,
    amount_cents INTEGER NOT NULL,
    subtotal_cents INTEGER NOT NULL DEFAULT 0,
    tax_cents INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
    journal_entry_id INTEGER REFERENCES journal_entries(id)
);

CREATE TABLE journal_entry_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id INTEGER NOT NULL REFERENCES journal_entries(id),
    account_id INTEGER NOT NULL REFERENCES accounts(id),
    analytic_account_id INTEGER REFERENCES analytic_accounts(id),
    debit_cents INTEGER NOT NULL DEFAULT 0,
    credit_cents INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE vendor_bills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id INTEGER NOT NULL UNIQUE REFERENCES purchase_orders(id),
    bill_date DATE NOT NULL,
    due_date DATE,
    amount_cents INTEGER NOT NULL,
    subtotal_cents INTEGER NOT NULL DEFAULT 0,
    tax_cents INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
    journal_entry_id INTEGER REFERENCES journal_entries(id)
);

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_bill_id INTEGER REFERENCES vendor_bills(id),
    customer_invoice_id INTEGER REFERENCES customer_invoices(id),
    method VARCHAR(20) NOT NULL,
    amount_cents INTEGER NOT NULL,
    date DATE NOT NULL,
    journal_entry_id INTEGER REFERENCES journal_entries(id),
    razorpay_order_id VARCHAR(64),
    razorpay_payment_id VARCHAR(64),
    CONSTRAINT ck_payment_one_document CHECK (
        (vendor_bill_id IS NOT NULL) <> (customer_invoice_id IS NOT NULL)
    ),
    CONSTRAINT ck_payment_method CHECK (method IN ('Cash', 'Bank', 'Razorpay')),
    CONSTRAINT ck_payment_amount_positive CHECK (amount_cents > 0)
);

CREATE TABLE stock_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    source_type VARCHAR(30) NOT NULL,
    source_id INTEGER NOT NULL,
    movement_date DATE NOT NULL,
    quantity_delta INTEGER NOT NULL,
    reason VARCHAR(255)
);

CREATE TABLE vendor_bill_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_bill_id INTEGER NOT NULL REFERENCES vendor_bills(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price_cents INTEGER NOT NULL,
    tax_percent INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE customer_invoice_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_invoice_id INTEGER NOT NULL REFERENCES customer_invoices(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price_cents INTEGER NOT NULL,
    tax_percent INTEGER NOT NULL DEFAULT 0
);

-- Indexes used by the application's ORM migrations.
CREATE INDEX ix_accounts_id ON accounts(id);
CREATE INDEX ix_analytic_accounts_id ON analytic_accounts(id);
CREATE INDEX ix_contacts_id ON contacts(id);
CREATE INDEX ix_products_id ON products(id);
CREATE INDEX ix_budgets_id ON budgets(id);
CREATE INDEX ix_journals_id ON journals(id);
CREATE INDEX ix_purchase_orders_id ON purchase_orders(id);
CREATE INDEX ix_sales_orders_id ON sales_orders(id);
CREATE INDEX ix_users_id ON users(id);
CREATE INDEX ix_users_email ON users(email);
CREATE INDEX ix_users_login_id ON users(login_id);
CREATE INDEX ix_journal_entries_id ON journal_entries(id);
CREATE INDEX ix_purchase_order_items_id ON purchase_order_items(id);
CREATE INDEX ix_sales_order_items_id ON sales_order_items(id);
CREATE INDEX ix_customer_invoices_id ON customer_invoices(id);
CREATE INDEX ix_journal_entry_lines_id ON journal_entry_lines(id);
CREATE INDEX ix_vendor_bills_id ON vendor_bills(id);
CREATE INDEX ix_payments_id ON payments(id);
CREATE INDEX ix_stock_movements_id ON stock_movements(id);
CREATE INDEX ix_vendor_bill_lines_id ON vendor_bill_lines(id);
CREATE INDEX ix_customer_invoice_lines_id ON customer_invoice_lines(id);
